[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  plerup/EspSoftwareSerial @ ^8.2.0
build_flags =
  -DCORE_DEBUG_LEVEL=0

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = uart-logger.local
upload_flags =
  --auth=uartlogger
  --host_ip=192.168.31.59
